//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliriumBot {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeliriumBot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я;Этот бокал для тебя;2
        ///Ты;Этот бокал передай другу;2
        ///Леди;Все дамы, присутствующие за столом пьют;2
        ///Джентельмены;Когда выпадает карта \&quot;Джентельмены\&quot;, все мущины присутствующие за столом пьют;2
        ///Тост;Произносишь тост, все игроки выпивают;2
        ///Передай налево;Игрок, сидящий слева от тебя пьет;2
        ///Передай направо;Игрок, сидящий справа от тебя пьет;2
        ///Вызов;Выбираешь игрока, который пьет вместе с тобой;1
        ///Все на пол;Все игроки должны коснуться пола. Последний коснувшийся пола пьет;3
        ///Прозвище;Придумываешь про [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало новой игры!.
        /// </summary>
        internal static string NewGameStart {
            get {
                return ResourceManager.GetString("NewGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ни одна карта из колоды не была разыграна. Для розыгрыша карты наберите &apos;/next&apos;..
        /// </summary>
        internal static string NoPreviousCard {
            get {
                return ResourceManager.GetString("NoPreviousCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колода закончилась. Для начала новой наберите &apos;/restart&apos;..
        /// </summary>
        internal static string SetEnded {
            get {
                return ResourceManager.GetString("SetEnded", resourceCulture);
            }
        }
    }
}
